
env:
  global:
  - FFMPEG_VERSION: '3.3.1'
  - IMAGEMAGICK_VERSION: '6.9.8-9'
  - NJOBS_STACK: '4'

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - $HOME/opt

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      # for GHC
      - libgmp-dev

      # for building ffmpeg
      - nasm
      - yasm

      # for imagemagick
      - libjpeg-dev
      - libpng-dev
      - libgif-dev

before_install:
  # update PATH so that our updated dependencies are found
  - export PATH=$HOME/opt/bin:$PATH

  # check if Imagemagick is already sufficient version, if not install it from source
  - ./spec/travis-install-imagemagick.sh

  # dito for FFMpeg
  - ./spec/travis-install-ffmpeg.sh

  # update library paths for programs
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include
  - export PKG_CONFIG_PATH=$HOME/opt/lib/pkgconfig:$PKG_CONFIG_PATH

  # download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# build dependencies
install:
  - stack -j ${NJOBS_STACK} --no-terminal --install-ghc build --only-dependencies

# build the package, its tests, and its docs and run the tests
script:
  - stack -j ${NJOBS_STACK} --no-terminal test
