
env:
  global:
  - IMAGEMAGICK_VERSION: '6.9.8-9'
  - LIBWEBP_VERSION: '0.5.1'

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - $HOME/opt

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      # for GHC
      - libgmp-dev

      # for ffmpeg-light
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libswscale-dev
      - libavdevice-dev

      # for imagemagick
      - libjpeg-dev
      - libpng-dev
      - libgif-dev

before_install:
  # Update PATH so that travis can find newer imagemagick
  - export PATH=$HOME/opt/bin:$PATH

  # Checks if Imagemagick is already sufficient version
  # If not installs it from the sources
  - ./spec/travis-install-imagemagick.sh

  # Update library paths for programs
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include
  - export PKG_CONFIG_PATH=$HOME/opt/lib/pkgconfig:$PKG_CONFIG_PATH

  - pkg-config --modversion MagickWand
  - pkg-config --cflags MagickWand
  - pkg-config --cflags MagickCore

  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Build dependencies
install:
  - stack --no-terminal --install-ghc test --only-dependencies

# Build the package, its tests, and its docs and run the tests
script:
  - stack --no-terminal test --haddock --no-haddock-deps
